[application]
name = "Sabin's Website"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "static"

[web.app]

# base_path = "."


[web.watcher]

watch_path = ["src", "assets", "index.html"]
index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["/tailwind.css"]

# Javascript code file
script = []

assets = ["static"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
